#! /usr/bin/env bash

# Use brightnessctl to naturally adjust laptop screen brightness and send a notification

currentbrightness=$(brightnessctl -e4 -m | awk -F, '{print substr($4, 0, length($4)-1)}')
if [ "$currentbrightness" -lt 30 ] && [ "$1" = "down" ]; then exit 1; fi

send_notification() {
  brightness=$(brightnessctl -e4 -m | awk -F, '{print substr($4, 0, length($4)-1)}')
  dunstify -a "Backlight" -u low -r 9994 -h int:value:"$brightness" -i "brightness" "Brightness: $brightness%" -t 1000
}

case $1 in
up)
  brightnessctl -e4 set 5%+ || exit 1
  send_notification
  ;;
down)
  brightnessctl -e4 set 5%- || exit 1
  send_notification
  ;;
esac
