#! /bin/bash
#
# Fuzzy find through dotfiles and scripts

find ~/dotfiles ~/scripts \
  -maxdepth 3 \
  -type f \
  -not -path '*/foot/themes/*' \
  -not -path '*/.git/*' |
  fzf --cycle --border=rounded --preview='bat $LINES {}' |
  xargs -r -o nvim
