#! /usr/bin/env bash
#
# For River
# Send notification of all running programs app id via lwst
#
# notify-send "$(lswt | awk 'NR > 1 {print $2}' | sort)"
#
# This awk, cut, sort command basically list the items in increase string length
notify-send "$(lswt | awk 'NR > 1 {print $2}' | awk '{ print length, $0 }' | sort -n | cut -d' ' -f2-)"
