#! /usr/bin/env bash

wall=$(find ~/wallpapers/Images/ -maxdepth 1 | shuf -n 1)
killall swaybg
cp "$wall" ~/.config/wall.png && swaybg -m fill -i "$wall" &
wal -n -e -a 80 -i "$HOME/.config/wall.png" && swaync-client -rs
