#! /usr/bin/env bash

wall=$(find ~/wallpapers/Images/ -maxdepth 1 | shuf -n 1)

cp "$wall" ~/.config/wall.png &&
  swww img "$wall" \
    --transition-type=any \
    --transition-step=60 \
    --transition-fps=60 \
    --transition-duration=.7 &&
  wal -n -e -a 80 -i "$HOME/.config/wall.png" && swaync-client -rs
