#! /usr/bin/env bash

wall=$(find ~/wallpapers/Images/ -maxdepth 1 | shuf -n 1)
# path="/home/sumit/wallpapers/Images/$wall"

cp "$wall" ~/.config/wall.png &&
  swww img "$wall" \
    --transition-type=any \
    --transition-step=30 \
    --transition-fps=60 \
    --transition-duration=1 &&
  hellwal --no-cache -i "$wall"
