#! /usr/bin/env bash
#
# Update mirrorlist for arch

sudo reflector --verbose \
  --latest 10 \
  --fastest 10 \
  --age 10 \
  --download-timeout 10 \
  --protocol https \
  --sort rate \
  --save /etc/pacman.d/mirrorlist
