#! /usr/bin/env bash

# If using swaybg
#
# killall swaybg
# cp "$1" ~/.config/wall.png && swaybg -m fill -i "$1" &
#
# With Swww, Have swww-daemon running
cp "$1" ~/.config/wall.png &&
  swww img "$1" \
    --transition-type=any \
    --transition-step=30 \
    --transition-fps=60 \
    --transition-duration=1 &&
  hellwal --no-cache -i "$1" -b 0.3
