#! /usr/bin/env bash

# OCR script

# Script to take an area screenshot with grim+slurp, and read text contexts
# using tesseract OCR
if ! command -v tesseract >/dev/null 2>&1; then
  notify-send -t 1500 "Tesseract is not installed"
  exit 1
fi

location=$(mktemp /tmp/image-XXXXXXXX.png)

if ! grim -g "$(slurp -d)" "$location"; then
  notify-send -t 1500 "No region selected"
  rm -f "$location"
  exit 1
fi

tesseract "$location" "$location" --psm 6

if [ -s "$location".txt ]; then
  tr '\n' ' ' <"$location".txt | wl-copy
  notify-send -t 1500 "Text copied from Image"
else
  notify-send -t 1500 "No text found in image"
fi

rm -f "$location" "$location".txt
