#! /usr/bin/env bash

# Change Volume and Send Nice notification
case $1 in
up)
  pamixer -i 5
  ;;
down)
  pamixer -d 5
  ;;
mute)
  pamixer --toggle-mute
  ;;
esac

# Arbitrary but unique message tag
msgTag="myvolume"

volume="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"

if [[ "$volume" == 0 || "$mute" == "true" ]]; then
  notify-send -u low -t 1000 -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted"
else
  notify-send -u low -t 1000 -i audio-volume-high -h string:x-canonical-private-synchronous:$msgTag -h int:value:"$volume" "Volume: ${volume}%"
fi
